services:
  golang:
    image: golang:1.24-bookworm
    container_name: stampkeeper
    volumes:
      - "/home/bird/stampkeeper:/usr/src/stampkeeper"
    ports:
      - "8080:8080"
    working_dir: /usr/src/stampkeeper
    restart: unless-stopped
    command: "go run main.go"
